### PR TITLE
docs: ADR about CMS/analytics platform auth

### LINKED ISSUE #99: ADR: strategy for CMS/analytics auth
Write ADR outlining the strategy for implementing auth across the CMS and analytics platforms

### PR DESCRIPTION
**Pull request by suzubara**
## Description 

ADR about our chosen strategy for handling authentication & authorization on supporting platforms.

Fixes #99

### CODE REVIEW

**Comment by noahfirth** [comment]
I made an edit for clarity. @suzubara, if you would check it out and make sure I did not misrepresent anything, that would be awesome!

**Comment by suzubara** [comment]
@noahfirth OH yes, I forgot to edit that part! thank you!

**Review by noahfirth — APPROVED** [review]
This looks good to me!

**Review by abbyoung — APPROVED** [review]
💯

**Pull request merged**
